[flow] Delete js_of_ocaml usage
Summary:
No longer needed since we moved to rust. OSS build for these targets have already been eliminated.

Changelog: [internal]

Reviewed By: panagosg7

Differential Revision: D109360840

fbshipit-source-id: 620f7622e35db34febe0162d7897199aa28d96e2

diff --git a/packages/flow-parser/Makefile b/packages/flow-parser/Makefile
--- a/packages/flow-parser/Makefile
+++ b/packages/flow-parser/Makefile
@@ -12,13 +12,14 @@ clean:
 
 # copies flow_parser.js into place, either using a copy that was put in
 # dist/flow_parser.js externally (e.g. during a Circle CI build), or by
-# building it.
+# building it outside of internal builds.
 .PHONY: flow_parser.js
 flow_parser.js:
 	if [ -e dist/flow_parser.js ]; then \
 		[ $@ -nt dist/flow_parser.js ] || cp dist/flow_parser.js $@; \
 	elif [[ "${INTERNAL_BUILD}" -eq 1 ]]; then \
-		buck2 build @//mode/opt //flow/src/parser:flow_parser.js --out $@; \
+		echo "dist/flow_parser.js is required for internal builds"; \
+		exit 1; \
 	else \
 		$(MAKE) -C ../../src/parser js; \
 		cp ../../src/parser/flow_parser.js $@; \
